[variables]
    NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
    nixPkgs = ["python311", "python311Packages.pip", "pkg-config", "libGL", "glib", "tesseract"]

[phases.install]
    cmds = ["pip3 install -r requirements.txt"]

[start]
    cmd = "python3 server_main.py"
