[variables]
    NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
    nixPkgs = ["python312", "pkg-config", "libGL", "glib", "gcc", "libX11"]

[phases.install]
    dependsOn = ["setup"]
    cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install --no-cache-dir -r requirements.txt"]

[start]
    cmd = "python3 server_main.py"
